FROM node:22-slim
WORKDIR /app
RUN npm install -g pnpm
RUN npm install -g ts-node nodemon
COPY package.json pnpm-lock.yaml ./
COPY tsconfig.json ./
RUN pnpm install
EXPOSE 5002
CMD ["npm", "run", "dev"]